# Generated by Django 2.0.10 on 2019-06-22 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.IntegerField(default=1)),
                ('gas', models.IntegerField(default=4500000)),
                ('gas_price', models.IntegerField(default=45)),
            ],
        ),
        migrations.CreateModel(
            name='CollaboratorDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(max_length=66, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=44)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('hash', models.CharField(max_length=66, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='documents/%Y_%m', verbose_name='Documento')),
                ('tx_id', models.CharField(max_length=66, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=66, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SCInfo',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=42)),
                ('abi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SignUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(max_length=42)),
                ('passphrase', models.CharField(default='aabbcc11', max_length=30)),
                ('private_key', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user/%Y_%m')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='minter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SignUser'),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DocumentStatus'),
        ),
        migrations.AddField(
            model_name='collaboratordocument',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SignUser'),
        ),
        migrations.AddField(
            model_name='collaboratordocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Document'),
        ),
        migrations.AlterUniqueTogether(
            name='collaboratordocument',
            unique_together={('document', 'collaborator')},
        ),
    ]
