# Generated by Django 2.0.10 on 2019-07-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(max_length=66, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=44)),
                ('comment', models.TextField(max_length=500)),
                ('view', models.BooleanField(default=False)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SignUser')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Document')),
            ],
        ),
    ]
