# Generated by Django 2.0.10 on 2019-03-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuser',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
