# Generated by Django 2.0.10 on 2019-07-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_collaboratoraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratoraction',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DocumentStatus'),
        ),
    ]
