# Generated by Django 2.0.10 on 2019-04-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_signuser_private_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCInfo',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=42)),
                ('abi', models.TextField()),
            ],
        ),
    ]
