# Generated by Django 2.0.10 on 2019-04-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_scinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.IntegerField(default=1)),
                ('gas', models.IntegerField(default=4000000)),
                ('gas_price', models.IntegerField(default=41)),
            ],
        ),
    ]
