# Generated by Django 2.0.10 on 2019-05-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bcvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bcvalue',
            name='gas',
            field=models.IntegerField(default=4500000),
        ),
        migrations.AlterField(
            model_name='bcvalue',
            name='gas_price',
            field=models.IntegerField(default=45),
        ),
    ]
