# Generated by Django 2.0.10 on 2019-05-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190505_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SignUser')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Document')),
            ],
        ),
    ]
