# Generated by Django 2.0.10 on 2019-05-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_collaboratordocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratordocument',
            name='tx_id',
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='collaboratordocument',
            unique_together={('document', 'collaborator')},
        ),
    ]
