# Generated by Django 2.0.10 on 2019-05-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190506_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratordocument',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
